version: '3.8'
services:
  pynest-app:
    build: ./app
    image: pynest-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  pynest-app-genai:
    build: ./app-genai
    image: pynest-app-genai
    ports:
      - "8001:8000"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./app-genai:/app
      - app_genai_chromadb:/app/chroma_db
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  angular-app:
    build:
      context: ./app-angular
      dockerfile: Dockerfile
    image: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./app-angular:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: ng serve --host 0.0.0.0 --poll 2000 --disable-host-check

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pgdata:
  app_genai_chromadb:

networks:
  app-network:
    driver: bridge
