version: '3.8'
services:
  pynest-app:
    build: ./app
    image: pynest-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy

  pynest-app-genai:
    build: ./app-genai
    image: pynest-app-genai
    ports:
      - "8001:8000"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app-genai:/app
      - app_genai_uploads:/app/uploads
      - app_genai_summaries:/app/summaries
      - app_genai_chromadb:/app/chroma_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  app_genai_uploads:
  app_genai_summaries:
  app_genai_chromadb: